name: Build HCU Plugin Release

on:
  release:
    types: [published]

permissions:
  contents: write

env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Structure Spec-Compliant HCU Directory
        run: |
          mkdir -p /tmp/custom.tibber.monitor/src
          cp manifest.json /tmp/custom.tibber.monitor/
          cp package.json /tmp/custom.tibber.monitor/
          cp src/index.js /tmp/custom.tibber.monitor/src/
          
          cd /tmp/custom.tibber.monitor
          npm install --omit=dev

      - name: Create Spec-Compliant HCU TAR.GZ Bundle
        run: |
          cd /tmp
          tar --format=posix -czf hcu-tibber-plugin.tar.gz custom.tibber.monitor/
          mv hcu-tibber-plugin.tar.gz ${{ github.workspace }}/custom.tibber.monitor-1.13.0.tar.gz

      - name: Upload Asset to GitHub Release (Via Native GitHub CLI)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} ${{ github.workspace }}/custom.tibber.monitor-1.13.0.tar.gz --clobber
